name: Bump Patch and Open PR

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-patch-open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version in version.txt
        id: bump
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f version.txt ]]; then
            echo "version.txt not found" >&2
            exit 1
          fi
          VERSION=$(tr -d '\r' < version.txt | tr -d '\n')
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version in version.txt: '$VERSION' (expected X.Y.Z)" >&2
            exit 1
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "$NEW_VERSION" > version.txt
          git checkout -b bump-patch-v${NEW_VERSION}
          git add version.txt
          git commit -m "chore(release): bump version to ${NEW_VERSION}"
          git push origin bump-patch-v${NEW_VERSION}
          echo "new_version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): bump version to ${{ steps.bump.outputs.new_version }}"
          branch: bump-patch-v${{ steps.bump.outputs.new_version }}
          base: master
          title: "chore(release): bump version to ${{ steps.bump.outputs.new_version }}"
          body: "Automated patch version bump. Please review and merge."
